<?php
$customerId = Mage::getModel('customer/session')->getCustomerId();
$customerPoints = Mage::getModel('rewardpoints/account')->load($customerId);
?>
Your Points: <?= sprintf('%d',$customerPoints->getPointsCurrent()); ?>
<br/>
Total Points Accumulated: <?= sprintf('%d',$customerPoints->getPointsReceived()); ?>
<br/>
Total Points Spent: <?= sprintf('%d',$customerPoints->getPointsSpent()); ?>
<br/>